---
- hosts: localhost
  connection: local
  gather_facts: false

  roles:
    - gitlab-droplet

- hosts: gitlab_server
  remote_user: root
  gather_facts: false
  vars:
    default_packages:
      - vim
  roles:
    - secure

  tasks:
    - name: Wait for port 22 to become available.
      local_action: "wait_for port=22 host={{ inventory_hostname }}"

    - name: Install default packages.
      apt: state=installed pkg={{ item }}
      with_items: default_packages

