---
galaxy_info:
  author: Gregório Melo
  description: 
  company: Tecnologicamente Arretado
  license: BSD
  min_ansible_version: 1.2
  platforms:
  - name: Ubuntu
    versions:
    - trusty
  categories:
  - development
dependencies: []

