---
- name: Install fail2ban.
  apt: name=fail2ban state=present

- name: Ensure fail2ban is running and enabled on boot.
  service: name=fail2ban state=started enabled=yes

# SSH
- include: ssh.yml

# Autoupdate
- name: Install unattended upgrades package.
  apt: name=unattended-upgrades state=present

- name: Copy unattended-upgrades configuration files in place.
  template:
    src: "../templates/{{ item }}.j2"
    dest: "/etc/apt/apt.conf.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - 10periodic
    - 50unattended-upgrades
